@startuml
title US02 - SSD - Register Physician with Optional Profile Photo

autoactivate on
autonumber

actor "Administrator"
participant ":RestAPI" as System
activate Administrator

Administrator -> System : POST /api/physicians
System --> Administrator : 201 Created

deactivate Administrator
note right of System
- Registers a new physician with all required fields and an optional profile photo.
end note

@enduml
