@startuml
title US9 - SD - Generate Appointment Statistics by Age Group
autoactivate on
 autonumber
actor "Administrator"
participant ":controller:ReportController" as ReportController
participant ":auth:AuthHelper" as AuthHelper
participant ":service:ReportService" as ReportService
participant ":repo:AppointmentRepository" as AppointmentRepository
participant ":mapper:ReportMapper" as ReportMapper

"Administrator" -> ReportController : GET /api/reports/age-groups
ReportController -> AuthHelper : getCurrentUser()
AuthHelper --> ReportController : User


    ReportController -> ReportService : getAppointmentStatsByAgeGroup()
    ReportService -> AppointmentRepository : findAllAppointmentsWithPatients()
    AppointmentRepository --> ReportService : List<Appointment>
    ReportService -> ReportMapper : toAgeGroupStatsDTO(List<Appointment>)
    ReportMapper --> ReportService : List<AgeGroupStatsDTO>
    ReportService --> ReportController : List<AgeGroupStatsDTO>
    ReportController --> "Administrator" : 200 OK
    alt not ADMIN
        ReportController --> "Administrator" : 403 Forbidden

end
@enduml
