@startuml
'https://plantuml.com/sequence-diagram

title US03-SSD: Register a Physician

autoactivate on
autonumber

actor "Administrator" as Admin
participant ":RestAPI" as System

activate Admin

Admin -> System: POST /api/physicians
System --> Admin: 201 Created

@enduml
