@startuml
title US10 – SSD – List Upcoming Appointments
autoactivate on
autonumber
actor "Administrator"
participant ":RestAPI" as System

autonumber
"Administrator" -> System : GET /api/appointments/upcoming

    System --> "Administrator" : 200 OK
alt not ADMIN
    System --> "Administrator" : 403 Forbidden


end
@enduml