@startuml
title US14 - SD - View Appointment Details

autoactivate on
autonumber

actor "User"
participant ":controller:AppointmentController" as AppointmentController
participant ":helper:AuthHelper" as AuthHelper
participant ":service:AppointmentService" as AppointmentService
participant ":repo:AppointmentRepository" as AppointmentRepository
participant ":mapper:AppointmentMapper" as AppointmentMapper

activate User

User -> AppointmentController : GET /api/appointments/{appointmentId}
AppointmentController -> AuthHelper : getCurrentUser()
AuthHelper --> AppointmentController : User (role, userId)

AppointmentController -> AppointmentService : getAppointmentDetails(appointmentId, user)

alt if (user.role == ADMIN)
    AppointmentService -> AppointmentRepository : findById(appointmentId)
    AppointmentRepository --> AppointmentService : Appointment
    AppointmentService -> AppointmentMapper : toDTO(Appointment)
    AppointmentMapper --> AppointmentService : AppointmentDTO
    AppointmentService --> AppointmentController : AppointmentDTO
    AppointmentController --> User : 200 OK

else if (user.role == PATIENT)
    AppointmentService -> AppointmentRepository : findById(appointmentId)
    AppointmentRepository --> AppointmentService : Appointment
    AppointmentService -> AppointmentMapper : toDTO(Appointment)
    AppointmentMapper --> AppointmentService : AppointmentDTO
    AppointmentService --> AppointmentController : AppointmentDTO
    AppointmentController --> User : 200 OK
end
alt appointment not found
    AppointmentService --> AppointmentController : 404 Not Found
    AppointmentController --> User : 404 Not Found
    deactivate User

end
alt acess denied
            AppointmentController --> User : 403 Forbidden
            deactivate User
      
     end
@enduml
