@startuml
title US11 - SD - Calculate Average Appointment Duration per Physician
autoactivate on
 autonumber
actor "Administrator" as Admin
participant ":controller:AppointmentController" as AppointmentController
participant ":helper:AuthHelper" as AuthHelper
participant ":service:AppointmentService" as AppointmentService
participant ":repo:AppointmentRepository" as AppointmentRepository
participant ":mapper:AppointmentMapper" as AppointmentMapper

autonumber

Admin -> AppointmentController : GET /api/appointments/average-duration
AppointmentController -> AuthHelper : getCurrentUser()
AuthHelper --> AppointmentController : User

    AppointmentController -> AppointmentService : getAverageDurationsPerPhysician()
    AppointmentService -> AppointmentRepository : findAverageDurationPerPhysician()
    AppointmentRepository --> AppointmentService : List<Object[]> (physicianId, avgDuration)
    AppointmentService -> AppointmentMapper : toAverageDTOList(List<Object[]>)
    AppointmentMapper --> AppointmentService : List<PhysicianAverageDTO>
    AppointmentService --> AppointmentController : List<PhysicianAverageDTO>
    AppointmentController --> Admin : 200 OK + List<PhysicianAverageDTO>
alt User is not ADMIN
    AppointmentController --> Admin : 403 Forbidden
end

@enduml
