@startuml
title US05 - SD - Register a Patient with Photo and Health Concerns
autoactivate on
autonumber

actor "Anonymous User"
participant ":controller:PatientController" as PatientController
participant ":service:PatientService" as PatientService
participant ":repo:PatientRepository" as PatientRepository
participant ":repo:PhotoRepository" as PhotoRepository
participant ":mapper:PatientMapper" as PatientMapper

activate "Anonymous User"

"Anonymous User" -> PatientController : POST /api/v2/patients/register

PatientController -> PatientService : registerPatient(dto)

alt dataConsentGiven == false
  PatientService --> PatientController : 400 Bad Request ("Data consent is required")
  PatientController --> "Anonymous User" : 400 Bad Request
  deactivate "Anonymous User"
else
  PatientService -> PatientRepository : existsByEmail(dto.email)
  PatientRepository --> PatientService : Boolean (emailExists)

  alt email already exists
    PatientService --> PatientController : 409 Conflict ("Email already in use")
    PatientController --> "Anonymous User" : 409 Conflict
    deactivate "Anonymous User"
  else
    alt missing required health concerns or insurance
      PatientService --> PatientController : 400 Bad Request ("Missing required data")
      PatientController --> "Anonymous User" : 400 Bad Request
      deactivate "Anonymous User"
    else
      alt some healthConcern invalid (e.g. ongoing == false but no resolvedDate)
        PatientService --> PatientController : 400 Bad Request ("Invalid health concern data")
        PatientController --> "Anonymous User" : 400 Bad Request
        deactivate "Anonymous User"
      else

          PatientService -> PhotoRepository : save(photo)
          PhotoRepository --> PatientService : Photo


        PatientService -> PatientMapper : toDomain(dto)
        PatientMapper --> PatientService : Patient

        PatientService -> PatientRepository : save(Patient)
        PatientRepository --> PatientService : Patient (with ID)

        PatientService --> PatientController : PatientIdResponse
        PatientController --> "Anonymous User" : 201 Created
        deactivate "Anonymous User"
      end
    end
  end
end
@enduml
