@startuml
title US04 - SD - View Physician Details

autoactivate on
autonumber

actor "User"
participant ":controller:PhysicianController" as PhysicianController
participant ":helper:AuthHelper" as AuthHelper
participant ":service:PhysicianService" as PhysicianService
participant ":repo:PhysicianRepository" as PhysicianRepository
participant ":mapper:PhysicianMapper" as PhysicianMapper

activate User

User -> PhysicianController : GET /api/physicians/{id}
PhysicianController -> AuthHelper : getCurrentUser()
AuthHelper --> PhysicianController : User (role)
PhysicianController -> PhysicianService : getPhysicianDetails(id, user)

PhysicianService -> PhysicianRepository : findById(id)
PhysicianRepository --> PhysicianService : Physician

alt if(user.role == ADMIN)
    PhysicianService -> PhysicianMapper : toFullDTO(Physician)
    PhysicianMapper --> PhysicianService : FullPhysicianDTO
else if(user.role == PATIENT)
    PhysicianService -> PhysicianMapper : toLimitedDTO(Physician)
    PhysicianMapper --> PhysicianService : LimitedPhysicianDTO
end

PhysicianService --> PhysicianController : PhysicianDTO
PhysicianController --> User : 200 OK

@enduml
