@startuml
title US08 - SSD - View patient´s details

autoactivate on
autonumber

actor "User"
participant ":RestAPI" as System

activate User
User -> System : GET /api/patients/{id}
System --> User : 200 OK

@enduml
