@startuml
title US08 - SSD - View Appointment History with Details

autoactivate on
autonumber

actor "Authenticated Patient"
participant ":System"

activate "Authenticated Patient"

"Authenticated Patient" -> ":System" : GET /api/patients/me/appointments/history

alt Not Authenticated
    ":System" --> "Authenticated Patient" : 401 Unauthorized
else
    ":System" --> "Authenticated Patient" : 200 OK\nList<AppointmentHistoryDTO>
end

deactivate "Authenticated Patient"
@enduml
