@startuml
title US12 - SSD - Generate Monthly Reports
autoactivate on
autonumber
actor "Administrator"
participant ":RestAPI" as System

activate "Administrator"

"Administrator" -> System : GET /api/reports/appointments?month=YYYY-MM

System --> "Administrator" : 200 OK
alt not ADMIN
    System --> "Administrator" : 403 Forbidden
end
deactivate "Administrator"
@enduml
