@startuml
title US09 - SSD - Search Patient by Name

autoactivate on
autonumber

actor "Administrator" as Admin
participant ":RestAPI" as System

activate Admin

Admin -> System : GET /api/patients/search/by-name?name=
System --> Admin : 200 OK
alt User not authenticated or not ADMIN
    System --> Admin : 403 Forbidden
else alt Patient not found
    System --> Admin : 404 Not Found
end
@enduml
