@startuml
title US06 - SSD - Update a Physician´s Data

autoactivate on
autonumber

actor "Administrator"
participant ":RestAPI" as System
activate Administrator

Administrator -> System : PATCH /api/physicians/{id}
System --> Administrator : 200 OK

deactivate Administrator
note right of System
- Updates physician's full profile (name, contact, specialization, department, etc.)
end note

@enduml
