@startuml
title US05 - SD - Search Physicians by Name or Specialty 
autoactivate on
autonumber

actor "Patient"
participant ":controller:PhysicianController" as PhysicianController
participant ":helper:AuthHelper" as AuthHelper
participant ":service:PhysicianService" as PhysicianService
participant ":repo:PhysicianRepository" as PhysicianRepository
participant ":mapper:PhysicianMapper" as PhysicianMapper

activate Patient

Patient -> PhysicianController : GET /api/physicians?name={name}&specialty={specialty}
PhysicianController -> AuthHelper : getCurrentUser()
AuthHelper --> PhysicianController : User (role)
PhysicianController -> PhysicianService : searchPhysicians(name, specialty, user)

PhysicianService -> PhysicianRepository : searchByNameOrSpecialty(name, specialty)
PhysicianRepository --> PhysicianService : List<Physician>

PhysicianService -> PhysicianMapper : toLimitedDTOList(Physicians)
PhysicianMapper --> PhysicianService : LimitedPhysicianDTOList

PhysicianService --> PhysicianController : PhysicianDTOList
PhysicianController --> Patient : 200 OK

deactivate Patient
 alt list is empty
   PhysicianController -> PhysicianService : searchPhysicians(name, specialty, user)
   PhysicianService -> PhysicianRepository : searchByNameOrSpecialty(name, specialty)
   PhysicianRepository --> PhysicianService : List<Physician>
    PhysicianService --> PhysicianController : 404 Not Found
    PhysicianController --> Patient : 404 Not Found

  end
  deactivate Patient
@enduml
