apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: hap-physicians
  description: Gestão de médicos, consultas (appointments) e Event Sourcing com audit trail.
  annotations:
    # Link para o Swagger (Requisito do Slide 10 [cite: 186])
    prometheus.io/scrape: 'true'
spec:
  type: service
  lifecycle: production
  owner: hap-team
  system: hap-system
  providesApis:
    - hap-physicians-api
