@startuml
title US15 - SD - View the Appointment Records of a Patient

autoactivate on
autonumber

actor "Physician"
participant ":controller:AppointmentRecordController" as AppointmentRecordController
participant ":helper:AuthHelper" as AuthHelper
participant ":repo:PatientRepository" as PatientRepository
participant ":service:AppointmentRecordService" as AppointmentRecordService
participant ":repo:AppointmentRecordRepository" as AppointmentRecordRepository
participant ":mapper:AppointmentRecordMapper" as AppointmentRecordMapper

activate Physician

Physician -> AppointmentRecordController : GET /api/patients/{patientId}/records
AppointmentRecordController -> AuthHelper : getCurrentUser()
AuthHelper --> AppointmentRecordController : User (Physician )


    AppointmentRecordController -> PatientRepository : findById(patientId)
    PatientRepository --> AppointmentRecordController : Patient
    AppointmentRecordController -> AppointmentRecordService : listRecordsByPatient(patientId)
    AppointmentRecordService -> AppointmentRecordRepository : findByPatientId(patientId)
    AppointmentRecordRepository --> AppointmentRecordService : List<AppointmentRecord>
    AppointmentRecordService -> AppointmentRecordMapper : toDTO(List<AppointmentRecord>)
    AppointmentRecordMapper --> AppointmentRecordService : List<AppointmentRecordDTO>
    AppointmentRecordService --> AppointmentRecordController : List<AppointmentRecordDTO>
    AppointmentRecordController --> Physician : 200 OK


@enduml
