@startuml
title US04 - SSD - View Top 5 Physicians based on the number of appointments

autoactivate on
autonumber

actor "Administrator"
participant ":RestAPI" as System
activate Administrator

Administrator -> System : GET /api/physicians/top5?from=YYYY-MM-DD&to=YYYY-MM-DD
System --> Administrator : 200 OK

deactivate Administrator
note right of System
- Returns a list of the 5 physicians with the most appointments.
- Ordered descending by total number of appointments.
end note

@enduml
