apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: hap-appointmentrecords
  annotations:
    hap/description: "Gestão de registos clínicos de consultas completadas. Armazena diagnósticos, prescrições e notas médicas."

    backstage.io/view-url: "https://localhost:8083/swagger-ui/index.html"

    prometheus.io/scrape: 'true'

    java/version: "17"
    spring-boot/version: "3.3.0"
    deployment/strategy: "blue-green"

spec:
  type: service
  lifecycle: production
  owner: hap-team
  system: hap-system

  providesApis:
    - hap-appointmentrecords-api

  dependsOn:
    - component:hap-auth
    - component:hap-patients
    - component:hap-physicians
    - resource:hap-mongo
    - resource:hap-rabbitmq

---

apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: hap-appointmentrecords-api
  annotations:
    hap/description: "API REST para consulta e criação de registos médicos."
spec:
  type: openapi
  lifecycle: production
  owner: hap-team
  system: hap-system
  definition: |
    openapi: 3.0.1
    info:
      title: HAP Appointment Records API
      version: 1.0.0
    paths:
      /api/appointment-records:
        get:
          summary: Listar registos
          responses:
            '200':
              description: OK